version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /bin/bash -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
  
  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
