version: '3.8'
services:
  app:
    image: laravelsail/php81-composer:latest
    container_name: app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    env_file:
      - .env
    command: php artisan serve --host=0.0.0.0 --port=80

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vagas
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: